"""
Migration Validation & Approval Engine — Phase 4
================================================
Validates the code generated by the Phase 3 AI Migration Agent BEFORE any
source code is applied (Phase 5). It never re-runs migration, never regenerates
code, never compiles, and never touches the original project — it only inspects
the generated files (held in memory by the Phase 3 agent + staged on disk) and
prepares approval decisions.

Validation dimensions:
  1. Syntax        — parse/validate generated files, detect malformed/incomplete.
  2. Dependency    — missing target build manifest, broken internal imports,
                     circular dependencies (from the Phase 2 plan).
  3. Architecture  — folder hierarchy, naming, component mapping, layer coverage.
  4. Configuration — env / build / docker / config / deployment file validity.
  5. Consistency   — skipped, partial, empty, broken-mapping, duplicate files.
  6. Risk analysis — categorize each file SAFE / WARNING / HIGH RISK / MANUAL REVIEW.

The engine also runs the approval workflow and produces the approval output that
Phase 5 will consume.
"""

from __future__ import annotations

import ast
import json
import time
import logging
import asyncio
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple

from backend.models.schemas import (
    FileValidationIssue,
    FileValidationResult,
    ValidationSummary,
    ValidationReport,
    ValidationStatusResponse,
    ApprovalOutput,
)
from backend.services.migration_service import migration_service
from backend.services.migration_agent_service import migration_agent_service

logger = logging.getLogger(__name__)

VALIDATION_STEPS = [
    "Loading Generated Files",
    "Syntax Validation",
    "Dependency Validation",
    "Architecture Validation",
    "Configuration Validation",
    "Consistency Validation",
    "Risk Analysis",
    "Building Validation Report",
    "Validation Completed",
]

# Target language -> expected build/dependency manifest filenames.
TARGET_MANIFESTS = {
    "java": ["pom.xml", "build.gradle", "build.gradle.kts"],
    "python": ["requirements.txt", "pyproject.toml", "setup.py"],
    "c#": ["*.csproj", "*.sln"],
    "csharp": ["*.csproj", "*.sln"],
    "javascript": ["package.json"],
    "typescript": ["package.json"],
    "go": ["go.mod"],
    "rust": ["cargo.toml"],
    "c++": ["cmakelists.txt", "makefile"],
    "cpp": ["cmakelists.txt", "makefile"],
    "php": ["composer.json"],
}

# Extensions we treat as "code" for syntax validation.
_CODE_EXTS = {".py", ".java", ".cs", ".js", ".jsx", ".ts", ".tsx",
              ".go", ".rs", ".cpp", ".c", ".h", ".hpp", ".php", ".kt", ".rb"}
_BRACE_EXTS = {".java", ".cs", ".js", ".jsx", ".ts", ".tsx", ".go",
               ".rs", ".cpp", ".c", ".h", ".hpp", ".php", ".kt"}

# Marker written by the Phase 3 offline deterministic translator.
_OFFLINE_MARKER = "MIGRATED FILE (offline"


class MigrationValidationError(Exception):
    """Recoverable, user-facing validation error."""


class MigrationValidationService:
    """Validates generated migration output and runs the approval workflow."""

    def __init__(self) -> None:
        self.status = "idle"  # idle, validating, completed, failed
        self.progress = 0.0
        self.current_step = ""
        self.error_message = ""
        self.step_logs: List[Dict[str, Any]] = []

        self.session_id: Optional[str] = None
        self.report: Optional[ValidationReport] = None
        # generated_path -> FileValidationResult
        self._results: Dict[str, FileValidationResult] = {}
        self._order: List[str] = []

        self._lock = asyncio.Lock()
        self._active_task: Optional[asyncio.Task] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def trigger_validation(self) -> None:
        if self._active_task and not self._active_task.done():
            self._active_task.cancel()
        self._active_task = asyncio.create_task(self.run_validation())

    def get_status(self) -> ValidationStatusResponse:
        return ValidationStatusResponse(
            status=self.status,
            progress=round(self.progress, 1),
            current_step=self.current_step,
            step_logs=self.step_logs,
            error=self.error_message or None,
            report=self._current_report(),
        )

    def get_file_result(self, generated_path: str) -> Optional[Dict[str, Any]]:
        """Return one file's validation result + its generated content (Issue Viewer)."""
        norm = (generated_path or "").replace("\\", "/").strip("/")
        res = self._results.get(norm)
        if not res:
            return None
        gen = migration_agent_service.get_file(norm)
        return {
            "result": res,
            "generated_content": gen.generated_content if gen else "",
            "original_content": gen.original_content if gen else "",
            "language": gen.language if gen else res.language,
        }

    # --- Approval workflow --------------------------------------------

    def approve_file(self, generated_path: str) -> Dict[str, Any]:
        res = self._require_result(generated_path)
        if not res.auto_approvable:
            return {
                "success": False,
                "message": f"'{generated_path}' is '{res.risk}' and cannot be approved. "
                           f"Failed / manual-review files must be fixed or rejected.",
                "approval": res.approval,
            }
        res.approval = "approved"
        return {"success": True, "approval": "approved"}

    def reject_file(self, generated_path: str) -> Dict[str, Any]:
        res = self._require_result(generated_path)
        res.approval = "rejected"
        return {"success": True, "approval": "rejected"}

    def approve_all_safe(self) -> Dict[str, Any]:
        """Bulk-approve every pending auto-approvable (safe/warning) file.

        Files marked failed or manual_review are never auto-approved.
        """
        count = 0
        for res in self._results.values():
            if res.auto_approvable and res.approval == "pending":
                res.approval = "approved"
                count += 1
        return {"success": True, "approved": count}

    def reject_migration(self) -> Dict[str, Any]:
        """Reject every file (reject the whole migration)."""
        for res in self._results.values():
            res.approval = "rejected"
        return {"success": True, "rejected": len(self._results)}

    def get_approval_output(self) -> ApprovalOutput:
        """Build the approval output consumed by Phase 5."""
        approved, rejected, pending = [], [], []
        for path in self._order:
            res = self._results[path]
            entry = {
                "generated_path": res.generated_path,
                "original_path": res.original_path,
                "component_type": res.component_type,
                "language": res.language,
                "validation_status": res.validation_status,
                "risk": res.risk,
                "score": res.score,
            }
            if res.approval == "approved":
                approved.append(entry)
            elif res.approval == "rejected":
                rejected.append(entry)
            else:
                # Pending → surfaces for review (includes failed/manual-review).
                entry["reason"] = res.validation_status
                pending.append(entry)

        report = self.report
        metadata = {
            "session_id": self.session_id,
            "validation_score": report.validation_score if report else 0.0,
            "success_percentage": report.success_percentage if report else 0.0,
            "risk_level": report.risk_level if report else "Unknown",
            "total_files": len(self._order),
            "source_language": report.source_language if report else None,
            "target_language": report.target_language if report else None,
            "scope": report.scope if report else None,
        }
        return ApprovalOutput(
            session_id=self.session_id,
            staging_path=report.staging_path if report else None,
            target_language=report.target_language if report else None,
            generated_at=time.strftime("%Y-%m-%d %H:%M:%S"),
            approved_files=approved,
            rejected_files=rejected,
            pending_review_files=pending,
            validation_metadata=metadata,
            # Phase 5 may proceed once at least one file is approved and nothing
            # approved is still failing.
            ready_for_apply=len(approved) > 0,
        )

    def reset(self) -> None:
        if self._active_task and not self._active_task.done():
            self._active_task.cancel()
        self.status = "idle"
        self.progress = 0.0
        self.current_step = ""
        self.error_message = ""
        self.step_logs = []
        self.session_id = None
        self.report = None
        self._results = {}
        self._order = []

    # ------------------------------------------------------------------
    # Validation pipeline
    # ------------------------------------------------------------------

    async def run_validation(self) -> None:
        async with self._lock:
            try:
                self._reset_run_state()

                # --- Step 1: Load generated files (reuse Phase 3 output) ------
                self._log_step(5.0, "Loading Generated Files",
                               "Collecting generated files from the migration session.")
                gen_files = migration_agent_service.all_generated_files()
                if not gen_files:
                    raise MigrationValidationError(
                        "No generated migration output found. Run the AI Migration "
                        "Agent (Phase 3) before validating."
                    )
                plan = migration_service.active_plan
                self.session_id = migration_agent_service.session_id
                staging_path = migration_agent_service.staging_path

                # Working accumulator per file.
                acc: Dict[str, Dict[str, Any]] = {}
                for gf in gen_files:
                    acc[gf.generated_path] = {"gf": gf, "issues": [], "deps": [], "recs": []}
                    self._order.append(gf.generated_path)
                await asyncio.sleep(0.03)

                # --- Steps 2-6: validation passes ----------------------------
                self._log_step(18.0, "Syntax Validation", "Parsing generated files…")
                self._syntax_pass(acc, staging_path)
                await asyncio.sleep(0.03)

                self._log_step(34.0, "Dependency Validation",
                               "Checking imports, manifests and circular dependencies…")
                self._dependency_pass(acc, plan)
                await asyncio.sleep(0.03)

                self._log_step(50.0, "Architecture Validation",
                               "Verifying folder hierarchy, naming and layer coverage…")
                self._architecture_pass(acc, plan)
                await asyncio.sleep(0.03)

                self._log_step(64.0, "Configuration Validation",
                               "Validating config / build / deployment files…")
                self._configuration_pass(acc)
                await asyncio.sleep(0.03)

                self._log_step(78.0, "Consistency Validation",
                               "Detecting skipped, partial, empty and duplicate files…")
                self._consistency_pass(acc)
                await asyncio.sleep(0.03)

                # --- Step 7: Risk analysis / finalize per-file ---------------
                self._log_step(88.0, "Risk Analysis",
                               "Categorizing files (safe / warning / high risk / manual review)…")
                for path in self._order:
                    self._results[path] = self._finalize_file(acc[path])
                await asyncio.sleep(0.03)

                # --- Step 8: Build report ------------------------------------
                self._log_step(95.0, "Building Validation Report",
                               "Aggregating scores, issues and recommended actions…")
                self.report = self._build_report(plan, staging_path)
                await asyncio.sleep(0.03)

                # --- Step 9: Completed ---------------------------------------
                self._log_step(
                    100.0, "Validation Completed",
                    f"Score {self.report.validation_score}% · "
                    f"{self.report.summary.safe_files} safe, "
                    f"{self.report.summary.warnings} warning, "
                    f"{self.report.summary.manual_review} manual review, "
                    f"{self.report.summary.failed} failed."
                )
                self.status = "completed"

            except asyncio.CancelledError:
                logger.info("Validation cancelled.")
                self.status = "idle"
                raise
            except MigrationValidationError as exc:
                logger.warning(f"Validation aborted: {exc}")
                self.status = "failed"
                self.error_message = str(exc)
                self._log_step(self.progress, "Validation Failed", f"Error: {exc}")
            except Exception as exc:  # noqa: BLE001
                logger.error(f"Validation failed: {exc}", exc_info=True)
                self.status = "failed"
                self.error_message = str(exc)
                self._log_step(self.progress, "Validation Failed", f"Unexpected error: {exc}")

    # ------------------------------------------------------------------
    # 1. Syntax validation
    # ------------------------------------------------------------------

    def _syntax_pass(self, acc: Dict[str, Dict[str, Any]], staging_path: Optional[str]) -> None:
        for path, entry in acc.items():
            gf = entry["gf"]
            issues: List[FileValidationIssue] = entry["issues"]

            if gf.status == "skipped":
                continue  # not translated — handled in consistency pass

            content = gf.generated_content or ""
            ext = Path(gf.generated_path).suffix.lower()

            # Verify the file actually exists in the staging workspace.
            if staging_path:
                staged = Path(staging_path) / gf.generated_path
                if not staged.exists():
                    issues.append(FileValidationIssue(
                        category="syntax", severity="error",
                        message="Generated file is missing from the staging workspace.",
                    ))

            # Empty / whitespace-only.
            if not content.strip():
                issues.append(FileValidationIssue(
                    category="syntax", severity="error",
                    message="Generated file is empty.",
                ))
                continue

            # Offline deterministic stub → incomplete migration (manual review).
            if _OFFLINE_MARKER in content[:400] or gf.provider == "offline":
                issues.append(FileValidationIssue(
                    category="syntax", severity="warning",
                    message="File was produced by the offline fallback translator "
                            "(original code preserved as comments) — not a full "
                            "AI translation. Manual completion required.",
                ))

            # Incomplete-generation heuristics.
            low = content.lower()
            if "todo" in low or "notimplemented" in low or "not implemented" in low:
                issues.append(FileValidationIssue(
                    category="syntax", severity="warning",
                    message="Generated code contains TODO / not-implemented markers.",
                ))
            if gf.reason and "truncated" in gf.reason.lower():
                issues.append(FileValidationIssue(
                    category="syntax", severity="warning",
                    message="Source was truncated for the model context window — "
                            "output may be partial.",
                ))

            # Language-specific parsing.
            if ext == ".py":
                err = self._check_python(content)
                if err:
                    issues.append(FileValidationIssue(
                        category="syntax", severity="error",
                        message=f"Python syntax error: {err[1]}", line=err[0],
                    ))
            elif ext in _BRACE_EXTS:
                ok, msg = self._check_braces(content)
                if not ok:
                    issues.append(FileValidationIssue(
                        category="syntax", severity="warning",
                        message=f"Possible syntax problem: {msg} (heuristic).",
                    ))
            elif ext == ".json":
                try:
                    json.loads(content)
                except Exception as exc:  # noqa: BLE001
                    issues.append(FileValidationIssue(
                        category="syntax", severity="error",
                        message=f"Invalid JSON: {exc}",
                    ))

    @staticmethod
    def _check_python(content: str) -> Optional[Tuple[Optional[int], str]]:
        try:
            ast.parse(content)
            return None
        except SyntaxError as exc:
            return (exc.lineno, exc.msg)

    @staticmethod
    def _check_braces(content: str) -> Tuple[bool, str]:
        pairs = {")": "(", "]": "[", "}": "{"}
        opens = set(pairs.values())
        stack: List[str] = []
        in_str: Optional[str] = None
        prev = ""
        line_comment = False
        for ch in content:
            if line_comment:
                if ch == "\n":
                    line_comment = False
                prev = ch
                continue
            if in_str:
                if ch == in_str and prev != "\\":
                    in_str = None
            elif ch in ("'", '"', "`"):
                in_str = ch
            elif ch == "/" and prev == "/":
                line_comment = True
            elif ch == "#":
                line_comment = True
            elif ch in opens:
                stack.append(ch)
            elif ch in pairs:
                if not stack or stack[-1] != pairs[ch]:
                    return False, f"unbalanced '{ch}'"
                stack.pop()
            prev = ch
        if stack:
            return False, "unbalanced brackets"
        return True, "ok"

    # ------------------------------------------------------------------
    # 2. Dependency validation
    # ------------------------------------------------------------------

    def _dependency_pass(self, acc: Dict[str, Dict[str, Any]], plan) -> None:
        target = (plan.target_language if plan else "java").lower()
        generated_paths = {p for p in acc.keys()}
        generated_stems = {Path(p).stem.lower() for p in acc.keys()}

        # (a) Missing target build manifest → external deps can't be declared.
        manifests = TARGET_MANIFESTS.get(target, [])
        has_manifest = self._has_manifest(generated_paths, manifests)
        ext_deps = list(plan.external_dependencies) if plan else []
        if ext_deps and not has_manifest:
            # Attach the aggregate finding to the entry point (or first code file).
            anchor = self._pick_anchor(acc)
            if anchor:
                acc[anchor]["deps"].extend(ext_deps[:20])
                acc[anchor]["issues"].append(FileValidationIssue(
                    category="dependency", severity="warning",
                    message=f"No target build manifest ({' / '.join(manifests) or 'manifest'}) "
                            f"was generated to declare {len(ext_deps)} external dependency(ies).",
                    detail=", ".join(ext_deps[:15]),
                ))
                acc[anchor]["recs"].append(
                    f"Create a {manifests[0] if manifests else 'build manifest'} declaring the "
                    f"target-language equivalents of: {', '.join(ext_deps[:10])}."
                )

        # (b) Broken internal imports in each generated file.
        for path, entry in acc.items():
            gf = entry["gf"]
            if gf.status == "skipped" or not gf.generated_content:
                continue
            imports = self._extract_internal_imports(gf.generated_content, gf.language)
            for imp in imports:
                stem = Path(imp).stem.lower()
                if stem and stem not in generated_stems and imp.startswith("."):
                    entry["issues"].append(FileValidationIssue(
                        category="dependency", severity="warning",
                        message=f"Internal import '{imp}' has no matching generated file.",
                    ))

        # (c) Circular dependencies (best-effort, from Phase 2 plan).
        cycles = self._detect_cycles(plan)
        for group in cycles:
            for src in group:
                # Match plan path to a generated file by stem.
                for path, entry in acc.items():
                    if Path(path).stem.lower() == Path(src).stem.lower():
                        entry["issues"].append(FileValidationIssue(
                            category="dependency", severity="warning",
                            message="Participates in a circular dependency "
                                    f"({' → '.join(Path(s).name for s in group)}).",
                        ))
                        break

    @staticmethod
    def _has_manifest(paths: set, manifests: List[str]) -> bool:
        names = {Path(p).name.lower() for p in paths}
        for m in manifests:
            m = m.lower()
            if m.startswith("*."):
                if any(n.endswith(m[1:]) for n in names):
                    return True
            elif m in names:
                return True
        return False

    @staticmethod
    def _pick_anchor(acc: Dict[str, Dict[str, Any]]) -> Optional[str]:
        for path, entry in acc.items():
            if entry["gf"].status in ("new", "modified"):
                return path
        return next(iter(acc), None)

    @staticmethod
    def _extract_internal_imports(content: str, language: str) -> List[str]:
        import re
        out: List[str] = []
        for m in re.findall(r"(?:import|from|require)\s+['\"]?(\.[^\s'\";]+)", content):
            out.append(m)
        return out[:20]

    @staticmethod
    def _detect_cycles(plan) -> List[List[str]]:
        if not plan or not plan.internal_dependencies:
            return []
        # Build a stem-resolved adjacency graph.
        deps = plan.internal_dependencies
        keys = list(deps.keys())
        stem_to_key = {Path(k).stem.lower(): k for k in keys}
        graph: Dict[str, List[str]] = {k: [] for k in keys}
        for k, imports in deps.items():
            for imp in imports:
                tgt = stem_to_key.get(Path(imp).stem.lower())
                if tgt and tgt != k:
                    graph[k].append(tgt)

        cycles: List[List[str]] = []
        seen_pairs = set()
        for a in graph:
            for b in graph[a]:
                if a in graph.get(b, []):
                    pair = tuple(sorted((a, b)))
                    if pair not in seen_pairs:
                        seen_pairs.add(pair)
                        cycles.append([a, b])
        return cycles[:10]

    # ------------------------------------------------------------------
    # 3. Architecture validation
    # ------------------------------------------------------------------

    def _architecture_pass(self, acc: Dict[str, Dict[str, Any]], plan) -> None:
        for path, entry in acc.items():
            gf = entry["gf"]
            if not gf.original_path:
                continue
            orig_parent = str(Path(gf.original_path).parent).replace("\\", "/")
            gen_parent = str(Path(gf.generated_path).parent).replace("\\", "/")
            if orig_parent != gen_parent:
                entry["issues"].append(FileValidationIssue(
                    category="architecture", severity="warning",
                    message=f"Folder hierarchy changed: '{orig_parent}' → '{gen_parent}'.",
                ))
            orig_stem = Path(gf.original_path).stem
            gen_stem = Path(gf.generated_path).stem
            if orig_stem != gen_stem:
                entry["issues"].append(FileValidationIssue(
                    category="architecture", severity="warning",
                    message=f"Naming changed: '{orig_stem}' → '{gen_stem}'.",
                ))

        # Layer coverage — is any architectural layer entirely un-migrated?
        if plan:
            self._check_layer_coverage(acc, plan)

    def _check_layer_coverage(self, acc: Dict[str, Dict[str, Any]], plan) -> None:
        # Map original paths that were successfully translated.
        migrated_orig = {
            e["gf"].original_path for e in acc.values()
            if e["gf"].original_path and e["gf"].status in ("new", "modified")
        }
        comps = plan.components
        layer_map = {
            "Presentation (controllers/UI)": comps.controllers,
            "Business (services)": comps.services,
            "Data (repositories/entities)": comps.repositories + comps.entities,
        }
        anchor = self._pick_anchor(acc)
        for layer_name, files in layer_map.items():
            files = [f for f in files if f]
            if not files:
                continue
            covered = sum(1 for f in files if f in migrated_orig)
            if covered == 0 and anchor:
                acc[anchor]["issues"].append(FileValidationIssue(
                    category="architecture", severity="warning",
                    message=f"{layer_name} layer was not migrated "
                            f"({len(files)} file(s) skipped/failed).",
                ))

    # ------------------------------------------------------------------
    # 4. Configuration validation
    # ------------------------------------------------------------------

    def _configuration_pass(self, acc: Dict[str, Dict[str, Any]]) -> None:
        for path, entry in acc.items():
            gf = entry["gf"]
            if gf.status == "skipped":
                continue
            name = Path(gf.generated_path).name.lower()
            ext = Path(gf.generated_path).suffix.lower()
            content = gf.generated_content or ""
            is_config = (
                gf.component_type in ("config", "build")
                or ext in (".json", ".yml", ".yaml", ".env", ".xml", ".toml", ".ini", ".properties")
                or name in ("dockerfile", ".env", "makefile")
            )
            if not is_config:
                continue

            if not content.strip():
                entry["issues"].append(FileValidationIssue(
                    category="configuration", severity="error",
                    message="Configuration file is empty.",
                ))
                continue

            if ext == ".json":
                try:
                    json.loads(content)
                except Exception as exc:  # noqa: BLE001
                    entry["issues"].append(FileValidationIssue(
                        category="configuration", severity="error",
                        message=f"Invalid JSON configuration: {exc}",
                    ))
            elif name == "dockerfile":
                if "from " not in content.lower():
                    entry["issues"].append(FileValidationIssue(
                        category="configuration", severity="error",
                        message="Dockerfile has no FROM instruction.",
                    ))
            elif name == ".env":
                for i, line in enumerate(content.splitlines(), 1):
                    s = line.strip()
                    if s and not s.startswith("#") and "=" not in s:
                        entry["issues"].append(FileValidationIssue(
                            category="configuration", severity="warning",
                            message=f"Malformed .env entry (expected KEY=VALUE).", line=i,
                        ))
                        break
            elif ext in (".yml", ".yaml"):
                if "\t" in content:
                    entry["issues"].append(FileValidationIssue(
                        category="configuration", severity="warning",
                        message="YAML contains tab characters (use spaces).",
                    ))

    # ------------------------------------------------------------------
    # 5. Consistency validation
    # ------------------------------------------------------------------

    def _consistency_pass(self, acc: Dict[str, Dict[str, Any]]) -> None:
        # Duplicate detection (same generated basename in same folder).
        by_location: Dict[str, List[str]] = {}
        for path in acc:
            by_location.setdefault(path.lower(), []).append(path)

        for path, entry in acc.items():
            gf = entry["gf"]

            if gf.status == "skipped":
                entry["issues"].append(FileValidationIssue(
                    category="consistency", severity="info",
                    message=f"File was skipped during migration ({gf.reason or 'not translated'}).",
                ))
                continue

            if gf.status == "failed":
                entry["issues"].append(FileValidationIssue(
                    category="consistency", severity="error",
                    message=f"Migration generation failed: {gf.error or 'unknown error'}.",
                ))

            if gf.generated_content is not None and not gf.generated_content.strip():
                entry["issues"].append(FileValidationIssue(
                    category="consistency", severity="error",
                    message="Generated file has no content (partial migration).",
                ))

            if not gf.original_path:
                entry["issues"].append(FileValidationIssue(
                    category="consistency", severity="warning",
                    message="Generated file has no mapped original source (broken mapping).",
                ))

            if len(by_location.get(path.lower(), [])) > 1:
                entry["issues"].append(FileValidationIssue(
                    category="consistency", severity="warning",
                    message="Duplicate generated file path detected.",
                ))

    # ------------------------------------------------------------------
    # 6. Risk analysis / per-file finalize
    # ------------------------------------------------------------------

    def _finalize_file(self, entry: Dict[str, Any]) -> FileValidationResult:
        gf = entry["gf"]
        issues: List[FileValidationIssue] = entry["issues"]
        deps: List[str] = list(dict.fromkeys(entry["deps"]))
        recs: List[str] = list(dict.fromkeys(entry["recs"]))

        has_error = any(i.severity == "error" for i in issues)
        has_warning = any(i.severity == "warning" for i in issues)
        is_offline_or_incomplete = any(
            "offline fallback" in i.message.lower() or "manual completion" in i.message.lower()
            for i in issues
        )

        if gf.status == "skipped":
            validation_status, risk = "manual_review", "manual_review"
        elif gf.status == "failed" or has_error:
            validation_status, risk = "failed", "high_risk"
        elif is_offline_or_incomplete:
            validation_status, risk = "manual_review", "manual_review"
        elif has_warning:
            validation_status, risk = "warning", "warning"
        else:
            validation_status, risk = "passed", "safe"

        score_map = {"passed": 100.0, "warning": 75.0, "manual_review": 40.0, "failed": 0.0}
        score = score_map[validation_status]

        # Auto-approvable only for safe / warning.
        auto_approvable = risk in ("safe", "warning")

        # Default recommendations.
        if validation_status == "failed" and not recs:
            recs.append("Fix the reported errors or reject this file before applying.")
        if validation_status == "manual_review" and not recs:
            recs.append("Manually review and complete this file; it cannot be auto-approved.")

        return FileValidationResult(
            generated_path=gf.generated_path,
            original_path=gf.original_path,
            component_type=gf.component_type,
            language=gf.language,
            generation_status=gf.status,
            validation_status=validation_status,
            risk=risk,
            score=score,
            auto_approvable=auto_approvable,
            approval="pending",
            issues=issues,
            missing_dependencies=deps,
            recommendations=recs,
        )

    # ------------------------------------------------------------------
    # Report building
    # ------------------------------------------------------------------

    def _build_report(self, plan, staging_path: Optional[str]) -> ValidationReport:
        results = [self._results[p] for p in self._order]
        total = len(results)

        summary = ValidationSummary(
            total_files=total,
            passed=sum(1 for r in results if r.validation_status == "passed"),
            warnings=sum(1 for r in results if r.validation_status == "warning"),
            failed=sum(1 for r in results if r.validation_status == "failed"),
            manual_review=sum(1 for r in results if r.validation_status == "manual_review"),
            safe_files=sum(1 for r in results if r.risk == "safe"),
            high_risk=sum(1 for r in results if r.risk == "high_risk"),
            syntax_errors=sum(1 for r in results for i in r.issues
                              if i.category == "syntax" and i.severity == "error"),
            dependency_issues=sum(1 for r in results for i in r.issues if i.category == "dependency"),
            architecture_issues=sum(1 for r in results for i in r.issues if i.category == "architecture"),
            configuration_issues=sum(1 for r in results for i in r.issues if i.category == "configuration"),
            consistency_issues=sum(1 for r in results for i in r.issues if i.category == "consistency"),
        )

        validation_score = round(sum(r.score for r in results) / total, 1) if total else 0.0
        success_percentage = round(
            ((summary.passed + summary.warnings) / total) * 100, 1
        ) if total else 0.0

        if summary.failed > 0:
            risk_level = "High"
        elif summary.manual_review > 0:
            risk_level = "Medium — Manual Review Required"
        elif summary.warnings > 0:
            risk_level = "Medium"
        else:
            risk_level = "Low"

        # Aggregate issue lists.
        syntax_errors, arch_issues, config_issues, consistency_issues = [], [], [], []
        missing_deps: List[str] = []
        for r in results:
            for i in r.issues:
                rec = {"file": r.generated_path, "message": i.message, "line": i.line, "severity": i.severity}
                if i.category == "syntax" and i.severity == "error":
                    syntax_errors.append(rec)
                elif i.category == "architecture":
                    arch_issues.append(rec)
                elif i.category == "configuration":
                    config_issues.append(rec)
                elif i.category == "consistency":
                    consistency_issues.append(rec)
            missing_deps.extend(r.missing_dependencies)
        missing_deps = list(dict.fromkeys(missing_deps))

        recommended = self._recommended_actions(summary, missing_deps)

        report = ValidationReport(
            session_id=self.session_id,
            staging_path=staging_path,
            source_language=plan.source_language if plan else None,
            target_language=plan.target_language if plan else None,
            scope=plan.scope if plan else None,
            generated_at=time.strftime("%Y-%m-%d %H:%M:%S"),
            validation_score=validation_score,
            success_percentage=success_percentage,
            risk_level=risk_level,
            summary=summary,
            files=results,
            missing_dependencies=missing_deps,
            syntax_errors=syntax_errors,
            architecture_issues=arch_issues,
            configuration_issues=config_issues,
            consistency_issues=consistency_issues,
            recommended_actions=recommended,
        )
        report.report_markdown = self._report_markdown(report)
        return report

    @staticmethod
    def _recommended_actions(summary: ValidationSummary, missing_deps: List[str]) -> List[str]:
        actions: List[str] = []
        if summary.failed:
            actions.append(f"Resolve {summary.failed} failed file(s) (syntax/empty/generation errors) "
                           f"or reject them before applying.")
        if summary.manual_review:
            actions.append(f"Manually review {summary.manual_review} file(s) marked for review "
                           f"(offline stubs / skipped / incomplete) — these cannot be auto-approved.")
        if missing_deps:
            actions.append(f"Declare {len(missing_deps)} external dependency(ies) in a target build "
                           f"manifest before applying.")
        if summary.architecture_issues:
            actions.append(f"Review {summary.architecture_issues} architecture deviation(s) "
                           f"(folder/naming/layer coverage).")
        if summary.safe_files and not summary.failed:
            actions.append(f"Approve the {summary.safe_files} safe file(s) to prepare them for Phase 5 (Apply).")
        if not actions:
            actions.append("All files validated cleanly — ready to approve and hand off to Phase 5.")
        return actions

    @staticmethod
    def _report_markdown(r: ValidationReport) -> str:
        s = r.summary
        return f"""
# MIGRATION VALIDATION REPORT

**Session:** `{r.session_id or 'n/a'}`
**Migration:** **{r.source_language} → {r.target_language}** (scope: `{r.scope}`)
**Generated:** {r.generated_at}
**Validation Score:** **{r.validation_score}%**  |  **Success:** {r.success_percentage}%  |  **Risk:** {r.risk_level}

---

## 1. Migration Summary
- **Total Files Validated:** {s.total_files}
- **Passed (Safe):** {s.passed}
- **Warnings:** {s.warnings}
- **Manual Review:** {s.manual_review}
- **Failed:** {s.failed}

## 2. Issue Breakdown
- **Syntax Errors:** {s.syntax_errors}
- **Dependency Issues:** {s.dependency_issues}
- **Architecture Issues:** {s.architecture_issues}
- **Configuration Issues:** {s.configuration_issues}
- **Consistency Issues:** {s.consistency_issues}

## 3. Missing Dependencies
{chr(10).join(f"- `{d}`" for d in r.missing_dependencies[:20]) or "- None detected"}

## 4. Recommended Actions
{chr(10).join(f"- {a}" for a in r.recommended_actions)}

---
> No source files were modified. Approve safe files to prepare the migration for Phase 5 (Apply).
""".strip()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _current_report(self) -> Optional[ValidationReport]:
        # Keep approval state fresh inside the report's file list.
        if self.report:
            self.report.files = [self._results[p] for p in self._order]
        return self.report

    def _require_result(self, generated_path: str) -> FileValidationResult:
        norm = (generated_path or "").replace("\\", "/").strip("/")
        res = self._results.get(norm)
        if not res:
            raise MigrationValidationError(f"No validation result for '{generated_path}'.")
        return res

    def _reset_run_state(self) -> None:
        self.status = "validating"
        self.progress = 0.0
        self.current_step = ""
        self.error_message = ""
        self.step_logs = []
        self.report = None
        self._results = {}
        self._order = []

    def _log_step(self, progress: float, step_name: str, detail: str) -> None:
        self.progress = progress
        self.current_step = step_name
        self.step_logs.append({
            "step": step_name,
            "detail": detail,
            "progress": round(progress, 1),
            "timestamp": time.strftime("%H:%M:%S"),
        })


# Global singleton instance
migration_validation_service = MigrationValidationService()
